# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'UD Unggas Sari Utama' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UD Unggas Sari Utama

	pod 'SwiftUICharts'


end
